apiVersion: v1
kind: Service
metadata:
  name: matrix
spec:
  type: NodePort
  selector:
    app: synapse
  ports:
  - name: http
    targetPort: 8008
    port: 80
  - name: federation
    targetPort: 8448
    port: 8448
