apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-env
data:
  SERVER_NAME: "isra17.xyz"
  REPORT_STATS: "no"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-lego
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  # modify this to specify your address
  lego.email: "cert@isra17.xyz"
  # configre letsencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
