apiVersion: v1
kind: Service
metadata:
  name: nfs-server-ss
spec:
  selector:
    app: nfs-server
  clusterIP: None
apiVersion: v1
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  selector:
    app: nfs-server
  clusterIP: 10.31.246.107
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  serviceName: nfs-server-ss
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-data
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
      volumes:
        - name: nfs-data
          gcePersistentDisk:
            pdName: nfs-data-pd
            fsType: ext4
