apiVersion: v1
kind: Service
metadata:
  name: matrix-appservice-slack
spec:
  selector:
    app: matrix-appservice-slack
  ports:
  - name: http
    port: 9999
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: matrix-appservice-slack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: matrix-appservice-slack
    spec:
      containers:
      - name: matrix-appservice-slack
        image: isra17/matrix-puppet-slack-docker
        ports:
        - name: service
          containerPort: 9999
        env:
        - name: APPSERVICE_URL
          value: http://matrix-appservice-slack:9999
        - name: MATRIX_LOCALPART
          valueFrom:
            secretKeyRef:
              name: matrix-creds
              key: MATRIX_LOCALPART
        - name: MATRIX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: matrix-creds
              key: MATRIX_PASSWORD
        volumeMounts:
          - name: nfs-data
            mountPath: /app/config.json
            subPath: config.json
          - name: nfs-data
            mountPath: /data
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
      volumes:
        - name: nfs-data
          nfs:
            server: 10.31.246.107
            path: "/slack/"


